[package]

name = "unicase"
version = "2.3.0" # don't forget to update html_root_url
authors = ["Sean McArthur <sean@seanmonstar.com>"]
description = "A case-insensitive wrapper around strings."
repository = "https://github.com/seanmonstar/unicase"
license = "MIT/Apache-2.0"
keywords = ["lowercase", "case", "case-insensitive", "case-folding"]

exclude = [
    "scripts/*"
]

build = "build.rs"

[build-dependencies]
version_check = "0.1"

[dev-dependencies]
criterion = "0.2.10"

[features]
nightly = []

[[bench]]
name = "bench"
harness = false
